
create table AgentPolicy
(
   AgentID INT REFERENCES Agent(AgentID),
   PolicyID INT REFERENCES Policy(PolicyID),
   IsSplitAgent INT,
   constraint pk_agp primary Key(AgentID,PolicyID)
);


INSERT INTO AGENTPOLICY(AGENTID,POLICYID,IsSplitAgent)
VALUES(1,1,2);
INSERT INTO AGENTPOLICY(AGENTID,POLICYID,IsSplitAgent)
VALUES(1,3,1);
INSERT INTO AGENTPOLICY(AGENTID,POLICYID,IsSplitAgent)
VALUES(2,3,1);
INSERT INTO AGENTPOLICY(AGENTID,POLICYID,IsSplitAgent)
VALUES(2,1,1);
INSERT INTO AGENTPOLICY(AGENTID,POLICYID,IsSplitAgent)
VALUES(2,4,1);
INSERT INTO AGENTPOLICY(AGENTID,POLICYID,IsSplitAgent)
VALUES(2,5,1);
INSERT INTO AGENTPOLICY(AGENTID,POLICYID,IsSplitAgent)
VALUES(4,1,2);
INSERT INTO AGENTPOLICY(AGENTID,POLICYID,IsSplitAgent)
VALUES(4,3,1);
INSERT INTO AGENTPOLICY(AGENTID,POLICYID,IsSplitAgent)
VALUES(5,1,2);
INSERT INTO AGENTPOLICY(AGENTID,POLICYID,IsSplitAgent)
VALUES(5,2,1);
